### ISSUE TITLE
ImportError: cannot import name 'overlay_external_default_cfg' from 'timm.models.helpers' (/opt/conda/lib/python3.8/site-packages/timm/models/helpers.py)

### ISSUE THREAD

**Issue by 915067906** [scok30/vit-cil#2]
作者您好：您的工作非常有意思，但是在安装环境时，按照您给的版本号，出现一下问题
raceback (most recent call last):
  File "main.py", line 15, in <module>
    from continual.pod import _local_pod
  File "/workspace/ENCIL/vit-cil/continual/__init__.py", line 3, in <module>
    from continual import vit
  File "/workspace/ENCIL/vit-cil/continual/vit.py", line 31, in <module>
    from timm.models.helpers import build_model_with_cfg, overlay_external_default_cfg
ImportError: cannot import name 'overlay_external_default_cfg' from 'timm.models.helpers' (/opt/conda/lib/python3.8/site-packages/timm/models/helpers.py)

**Comment by scok30** [comment]
Thank you for your interest in our work. To improve the usability of our code, we will integrate it into the widely used non-exemplar class-incremental learning repository within the next two weeks. We hope this will address your concerns regarding library dependency versions. Please be patient, and thank you.

**Comment by scok30** [comment]
Thank you for your interest in our work. To improve the usability of our code, we will integrate it into the widely used non-exemplar class-incremental learning repository within the next two weeks. We hope this will address your concerns regarding library dependency versions. Please be patient, and thank you.
